ENG-1207 Create build pipeline for percona everest cli
percona/percona-everest-cli pull request #109
Opened 2023-08-23 07:28 UTC by adivinho

2023-08-23 07:28 UTC, it-percona-cla commented
[![CLA assistant check](https://cla-assistant.percona.com:443/pull/badge/not_signed)](https://cla-assistant.percona.com:443/percona/percona-everest-cli?pullRequest=109) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.percona.com:443/percona/percona-everest-cli?pullRequest=109) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.percona.com:443/check/percona/percona-everest-cli?pullRequest=109) it.</sub>

2023-08-23 08:43 UTC, michal-kralik reviewed
Thank you for your contribution.
Is the deployment meant to be run automatically on every new version?

2023-08-23 08:43 UTC, michal-kralik commented on packaging/LICENSE
> +
We have a `LICENSE` file in the root. Is there any reason we need a second license?

2023-08-23 08:43 UTC, michal-kralik commented on packaging/rpm/percona-everest-cli.spec
> +* Tue Aug 15 2023 Vadim Yalovets <vadim.yalovets> 0.1-1
Our versioning consists of 3 versions `0.1.0`. Does the spec support this?

2023-08-23 11:58 UTC, adivinho commented on packaging/LICENSE
> +
It has been modified to use already provided LICENSE file

2023-08-23 11:59 UTC, adivinho commented on packaging/rpm/percona-everest-cli.spec
> +* Tue Aug 15 2023 Vadim Yalovets <vadim.yalovets> 0.1-1
Fixed

2023-08-23 12:02 UTC, adivinho commented
> Thank you for your contribution. Is the deployment meant to be run automatically on every new version?

There is no such task in the ticket.
Please create a new ticket in order to add an additional pipeline to run this job if a new tag is added.

2023-08-23 14:37 UTC, michal-kralik approved these changes

2023-08-23 18:49 UTC, recharte requested changes
Hi @adivinho thank you very much for this, it looks great.

I know that you asked for and got a sign-off on the binary file and package description. However, last week, when we released everest v0.1.0, we decided that the binary will be called `everestctl` and I guess this wasn't communicated to you and you used `everest` throughout.
May you please rename it to `everestctl`? Sorry for the extra work.

2023-08-28 09:44 UTC, gen1us2k approved these changes
Thanks. Looks good but please take a look at Diogo's request for changes.

2023-08-29 07:22 UTC, adivinho commented
> Hi @adivinho thank you very much for this, it looks great.
> 
> I know that you asked for and got a sign-off on the binary file and package description. However, last week, when we released everest v0.1.0, we decided that the binary will be called `everestctl` and I guess this wasn't communicated to you and you used `everest` throughout. May you please rename it to `everestctl`? Sorry for the extra work.

It has been renamed.
e.g.
 
![Screenshot 2023-08-29 at 10 09 31](https://github.com/percona/percona-everest-cli/assets/25184101/566df440-f2c9-4070-8b2f-d4ec7eb59c12)

2023-08-29 07:36 UTC, recharte approved these changes
Thank you, great job @adivinho

2023-08-30 08:34 UTC, merged