EVEREST-633 Multi environment support
percona/percona-everest-cli pull request #211
Opened 2023-11-13 13:47 UTC by gen1us2k

**CHANGE DESCRIPTION**
---
**Problem:**
EVEREST-633

*Short explanation of the problem.*

**Related pull requests**

- [link]

**Cause:**
*Short explanation of the root cause of the issue if applicable.*

**Solution:**
*Short explanation of the solution we are providing with this PR.*

**CHECKLIST**
---
**Jira**
- [ ] Is the Jira ticket created and referenced properly?

**Tests**
- [ ] Is an Integration test/test case added for the new feature/change?
- [ ] Are unit tests added where appropriate?

2023-11-14 14:45 UTC, oksana-grishchenko commented on commands/install.go
> +	cmd.Flags().StringArray("namespaces", []string{}, "Namespaces list Percona Everest can manage")
Don't fully understand how to use the flag. 
The first run is clear - user pass the list of the namespaces, let's say it's `namespaceA` and `namespaceB`. What if one wants to add `namespaceC` or delete `namespaceA` later? I think adding/deleting option would be useful in a real life. 

If at this stage the flag is supposed to be used only for initial provisioning I believe we should catch later change attempts and show an error message.

2023-11-16 12:30 UTC, gen1us2k commented on commands/install.go
> +	cmd.Flags().StringArray("namespaces", []string{}, "Namespaces list Percona Everest can manage")
Let me explain
```
--namespace=percona-everest --namespaces=dev,prod
```

In that case, CLI deploys everest and everything else into percona-everest namespace and deploys operators, configures everything in `dev` and `prod` namespaces. Later, the end user can run
```
namespace=percona-everest --namespaces=staging,dev
```
The logic is the same and it will deploy operators into staging and dev

To uninstall something from any namespace I recommend using `uninstall` command because from the UX perspective, it is predictable. Install command do not need to delete anything and we can use either `uninstall` or `destroy` commands for that.

For the next iterations, I assume CLI needs to support different configurations per namespace, e.g.:
1. dev uses monitoring, pxc, psmdb
2. prod uses monitoring and pg, pxc

2023-11-22 09:45 UTC, oksana-grishchenko commented on commands/install.go
> +	cmd.Flags().StringArray("namespaces", []string{}, "Namespaces list Percona Everest can manage")
I don't get one thing. If first we run 
```
--namespace=percona-everest --namespaces=dev,prod
```
the configmap with dev,prod is created and persisted

then we run 
```
namespace=percona-everest --namespaces=staging,dev
```

and the configmap is rewritten so now it contains staging, dev but not prod. 
or the "Create" method merges data and works as "CreateOrUpdate" when being called more then once?

2023-11-23 12:32 UTC, recharte commented on commands/install.go
> +	cmd.Flags().StringArray("namespaces", []string{}, "Namespaces list Percona Everest can manage")
I think that maybe we could rename these to avoid ambiguity, `namespace` and `namespaces` is way too vague.
Suggestions:
1. `everest-namespace`, `managed-namespaces`
2. `primary-namespace`, `managed-namespaces`
3. `admin-namespace`, `managed-namespaces`
:shrug: 
@oksana-grishchenko @gen1us2k any other suggestions?

2023-11-23 12:32 UTC, recharte commented on pkg/install/install.go
> +		}
This doesn't belong here, this sets up the client for the main namespace, no need to run it more than once.

2023-11-23 12:32 UTC, recharte commented on pkg/install/install.go
> +func (o *Install) performProvisioning(ctx context.Context, namespace string) error {
I think we should split this function into the parts that are generic for all managed namespaces and the ones that are only meant to be run in the main namespace.

2023-11-23 12:32 UTC, recharte commented on pkg/install/install.go
> +			Resources: []string{"databaseclusters", "databaseclusterrestores"},
Why do we have `databaseclusterrestores` here if it's also specified below?
```suggestion
			Resources: []string{"databaseclusters"},
```

2023-11-28 08:24 UTC, gen1us2k commented on commands/install.go
> +	cmd.Flags().StringArray("namespaces", []string{}, "Namespaces list Percona Everest can manage")
It works as create or update when being called more than once

2023-11-29 13:08 UTC, oksana-grishchenko approved these changes
Looks good 👍 

If this is agreed to use "percona-everest" as the default constant namespace for everest operator, don't mind using this approach for handling several environments, left a few minor comments.

2023-11-29 13:08 UTC, oksana-grishchenko commented on pkg/kubernetes/kubernetes.go
> +		namespace := namespace
the `namespace` is also defined as the function parameter, and here it gets redeclared. It's loop scoped so there is no problem so far but it may lead to a confusion and tricky bugs in the future.

2023-11-29 13:24 UTC, gen1us2k commented on pkg/kubernetes/kubernetes.go
> +		a := a
Yep. Until moving to 1.22

2023-11-29 15:56 UTC, michal-kralik commented on pkg/install/install.go
> +	if err := o.createNamespace(everestNamespace); err != nil {
We shall not force a user to use a predefined namespace.
Can we please make this configurable?

2023-11-30 07:34 UTC, gen1us2k commented on pkg/install/install.go
> +	if err := o.createNamespace(everestNamespace); err != nil {
I agree that it should be configurable yet there's a corner case that exists right now. When the end user runs two commands

```
everestctl install --install-namespace percona-everest-dev --namespace dev --namespace staging
everestctl install --install-namespace percona-everest-prod --namespace prod --namespace bi
```

Everest should generate a service account for each installation and it's a bit out of scope for this stage. I communicated it with Peter and we agreed that we can do it later as well as having `everestctl namespace add` command.

We can make it configurable after BE changes

2023-12-02 07:56 UTC, michal-kralik commented on pkg/kubernetes/kubernetes.go
> +func (k *Kubernetes) PersistConfiguration(ctx context.Context, namespace string, namespaces []string, operatorsList []string) (bool, error) {
This approach is prone to race-conditions.
When this function runs in parallel, e.g. two CI/CD jobs triggering at the same time, one will overwrite the other.

I suggest we change the approach so we retain data consistency.

2023-12-05 12:49 UTC, michal-kralik commented on pkg/install/install.go
> +	if err != nil {
Can we move this before the `if updated` check so it's clear it belongs to the for loop?

2023-12-05 12:49 UTC, michal-kralik commented on pkg/kubernetes/kubernetes.go
> +	}
These lines are the same.
It appears the second one should have been about `operators`.

Can you please also add tests to make sure the data is updated properly?
Since the tests are passing, this does not seem to be covered.

2023-12-05 18:22 UTC, michal-kralik commented on pkg/install/install.go
> +		if updated {
This logic does not check for errors properly. The error on line 213 is ignored.

2023-12-05 18:25 UTC, michal-kralik reviewed
Can you please add tests per https://github.com/percona/percona-everest-cli/pull/211#discussion_r1415556551?

2023-12-06 07:38 UTC, gen1us2k commented
@michal-kralik I added them yesterday https://github.com/percona/percona-everest-cli/blob/3b6d7213f7ecb884e0855dce84d253ae70b6d59b/cli-tests/tests/flow/multi-namespace-mongo-operator.spec.ts#L72-L86

2023-12-06 10:27 UTC, michal-kralik commented on pkg/kubernetes/kubernetes.go
> +	}
The tests for operator look good.
Can we please also add tests for when the list of namespaces changes?
i.e. add/remove/no-change in namespaces?

2023-12-06 11:38 UTC, michal-kralik commented on pkg/install/install.go
> +	for _, namespace := range namespaces {
What is the reason we deploy monitoring per namespace?
Is it possible to have a single deployment only?

2023-12-06 11:38 UTC, michal-kralik commented on pkg/install/install.go
> +func (o *Install) provisionAllOperators(ctx context.Context, namespace string) error {
Can we please refactor this function? Its only job is to call another function.

2023-12-06 11:38 UTC, michal-kralik commented on pkg/install/install.go
> +	o.config.Namespaces = strings.Split(namespaces, ",")
In all places where we do this split, we shall as well trim the values.
Using `prod, dev` value fails as it cannot create a namespace " dev"

2023-12-06 11:44 UTC, gen1us2k commented on commands/uninstall.go
> +	cmd.Flags().StringArray("namespace", []string{}, "Namespaces list Percona Everest can manage")
Nothing because the flow for the uninstallation is not changed. I'll drop it

2023-12-06 12:01 UTC, gen1us2k commented on pkg/install/install.go
> +func (o *Install) provisionAllOperators(ctx context.Context, namespace string) error {
Done

2023-12-06 12:13 UTC, recharte commented on pkg/install/install.go
> +	if err := o.createNamespace(everestNamespace); err != nil {
This will be handled in [EVEREST-667](https://jira.percona.com/browse/EVEREST-667)

2023-12-06 12:24 UTC, michal-kralik commented on pkg/install/install.go
> +			Namespace:      everestNamespace,
Given the namespace is fixed, I think we shall revisit the `everestctl password reset` command and remove the `namespace`` flag.

2023-12-06 12:24 UTC, michal-kralik commented on commands/upgrade.go
> +	cmd.Flags().StringArray("namespace", []string{}, "Namespaces list Percona Everest can manage")
Can we use the config map so that user does not have list all namespaces?

2023-12-06 12:27 UTC, gen1us2k commented on pkg/install/install.go
> +			Namespace:      everestNamespace,
Sure, but I want to do this as a part of the upcoming PR after making BE changes to work fine. That's a great improvement yet it does not block the PR

2023-12-06 12:27 UTC, gen1us2k commented on pkg/install/install.go
> +	o.config.Namespaces = strings.Split(namespaces, ",")
Done

2023-12-06 12:28 UTC, gen1us2k commented on commands/upgrade.go
> +	cmd.Flags().StringArray("namespace", []string{}, "Namespaces list Percona Everest can manage")
Sure, but I want to do this as a part of the upcoming PR after making BE changes to work fine. That's a great improvement yet it does not block the PR

2023-12-06 12:31 UTC, michal-kralik commented on pkg/install/install.go
> +			Namespace:      everestNamespace,
Sounds good. Feel free to link a ticket here and resolve this conversion.

2023-12-06 12:32 UTC, recharte approved these changes
Good job Andrew.
I don't consider the remaining comments to be blockers and can be dealt with in a follow-up PR as you suggested. Approving :heavy_check_mark:

2023-12-06 12:33 UTC, michal-kralik commented on commands/upgrade.go
> +	cmd.Flags().StringArray("namespace", []string{}, "Namespaces list Percona Everest can manage")
Sounds good. Can you please link a ticket and resolve this conversation?

2023-12-06 12:39 UTC, michal-kralik requested changes

2023-12-06 12:39 UTC, michal-kralik commented on pkg/install/install.go
> -	}
I believe this should not have been removed

2023-12-06 13:20 UTC, gen1us2k commented on pkg/install/install.go
> -	}
Restored

2023-12-06 16:15 UTC, merged