EVEREST-230 Release pipeline for cli
percona/percona-everest-cli pull request #80
Opened 2023-08-08 13:14 UTC by gen1us2k

2023-08-08 13:14 UTC, it-percona-cla commented
[![CLA assistant check](https://cla-assistant.percona.com:443/pull/badge/not_signed)](https://cla-assistant.percona.com:443/percona/percona-everest-cli?pullRequest=80) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.percona.com:443/percona/percona-everest-cli?pullRequest=80) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.percona.com:443/check/percona/percona-everest-cli?pullRequest=80) it.</sub>

2023-08-08 15:00 UTC, michal-kralik commented
> @michal-kralik What integration test do you wanna see? It's just a pipeline stuff

For the new functionality - the `version` command.

2023-08-08 15:17 UTC, gen1us2k commented
@michal-kralik we will have more changes in this command and in the build process as well. Since the `version` command works only by providing build tags there's no point in having a basic integration test in case of having tests.

Also, it requires changes in the CI pipeline configuration to test this correctly and this is a draft way of having releases for the CLI since we do not have anything else. Later we may drop the version command and this pipeline at all because we can print version information without using version command

2023-08-08 15:27 UTC, gen1us2k commented on install.sh
> +chmod +x everestctl
It will be improved later. No idea right now and I chose the safest way

2023-08-08 15:45 UTC, recharte commented on install.sh
> +open http://127.0.0.1:8080
`open` also works on some distros but I don't think is as universal as `xdg-open`.

2023-08-08 15:46 UTC, recharte commented on Makefile
> +VERSION = ${IMAGE_VERSION}
Since you dropped the version command I don't think this used anywhere right now...

2023-08-08 15:47 UTC, recharte approved these changes

2023-08-08 15:51 UTC, recharte requested changes

2023-08-08 15:51 UTC, recharte commented on install.sh
> +arch=$(uname -m | tr '[:upper:]' '[:lower:]')
In my system this is `x86_64` and not `amd64` like you called in the release makefile target

2023-08-09 05:45 UTC, michal-kralik approved these changes

2023-08-09 05:45 UTC, merged